# Generated by Django 5.2.6 on 2025-12-04 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='WatchlistItem',
        ),
    ]
