# Generated by Django 5.2.6 on 2025-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_watchlist_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
