# Generated by Django 5.2.6 on 2025-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_watchlistitem_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
