# Generated by Django 5.2.6 on 2025-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_watchlistitem_user_rating_watchlistitem_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
