# Generated by Django 5.2.6 on 2025-12-10 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='profile_pic',
        ),
        migrations.AlterModelTable(
            name='profile_pic',
            table='profile_pic',
        ),
    ]
