# Generated by Django 5.2.6 on 2025-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_profile_profile_pic_alter_profile_pic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='image',
            field=models.ImageField(blank=True, default='default_profil.png', upload_to='profile_pics'),
        ),
        migrations.AlterModelTable(
            name='profile_pic',
            table=None,
        ),
    ]
